jobs:
- job: InvokeAPIJob
  displayName: 'Sudins API Job'
  pool: server # Use the server pool for agentless tasks
  steps:
  - task: InvokeRESTAPI@1
    inputs:
      connectionType: 'Sudinpm'
      method: 'GET'
      headers: '{"Content-Type": "application/json"}'
      waitForCompletion: 'false'
